"""initial_schema

Revision ID: 10911737759d
Revises: 
Create Date: 2026-05-06 16:09:44.619323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10911737759d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_identifier', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_identifier', name='uq_devices_device_identifier')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('health_vitals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('steps', 'heart_rate', 'sleep', 'calories', 'spo2', 'respiratory_rate', 'body_temperature', name='metric_type_enum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    sa.UniqueConstraint('device_id', 'metric_type', 'recorded_at', name='uq_health_vitals_device_metric_recorded_at')
    )
    op.create_index(op.f('ix_health_vitals_device_id'), 'health_vitals', ['device_id'], unique=False)
    op.create_index('ix_health_vitals_metric_type', 'health_vitals', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_vitals_recorded_at'), 'health_vitals', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_health_vitals_user_id'), 'health_vitals', ['user_id'], unique=False)
    op.create_index('ix_health_vitals_user_recorded_at_desc', 'health_vitals', ['user_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.execute(
        "SELECT create_hypertable('health_vitals', 'recorded_at', if_not_exists => TRUE, migrate_data => TRUE)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_vitals_user_recorded_at_desc', table_name='health_vitals')
    op.drop_index(op.f('ix_health_vitals_user_id'), table_name='health_vitals')
    op.drop_index(op.f('ix_health_vitals_recorded_at'), table_name='health_vitals')
    op.drop_index('ix_health_vitals_metric_type', table_name='health_vitals')
    op.drop_index(op.f('ix_health_vitals_device_id'), table_name='health_vitals')
    op.drop_table('health_vitals')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS metric_type_enum")
    # ### end Alembic commands ###
